### ISSUE TITLE
Agregar Readme

### ISSUE THREAD

**Issue by emiarias** [gazzpc/BackendProyecto3#18]
Proceso
Cuando ingresamos al repositorio

Resultado esperado
Visualizar el readme del repositorio con una descripción del proyecto y los integrantes del mismo.

Resultado actual
El repositorio no posee readme

Captura
![image](https://github.com/ColmanNicolas/BackendProyecto3/assets/18445151/4a7e0b00-9355-47ef-a846-e329e03fffbd)

**Comment by ColmanNicolas** [comment]
Archivo Readme.md creado
